package albedo

import (
	"github.com/genshinsim/gcsim/pkg/core/attacks"
	"github.com/genshinsim/gcsim/pkg/core/attributes"
	"github.com/genshinsim/gcsim/pkg/core/event"
	"github.com/genshinsim/gcsim/pkg/core/glog"
	"github.com/genshinsim/gcsim/pkg/core/info"
	"github.com/genshinsim/gcsim/pkg/core/player/character"
	"github.com/genshinsim/gcsim/pkg/enemy"
	"github.com/genshinsim/gcsim/pkg/modifier"
)

const (
	hexereiSkillKey    = "albedo-hexerei-skill"
	hexereiIsotomaKey  = "albedo-hexerei-isotoma"
	hexereiAurelithKey = "albedo-hexerei-aurelith"
)

// Transient Blossoms generated by Abiogenesis: Solar
// Isotoma deal 25% more DMG to opponents whose HP is below 50%.
func (c *char) a1() {
	if !c.Core.Combat.DamageMode {
		return
	}
	if c.Base.Ascension < 1 {
		return
	}
	m := make([]float64, attributes.EndStatType)
	m[attributes.DmgP] = 0.25
	c.AddAttackMod(character.AttackMod{
		Base: modifier.NewBase("albedo-a1", -1),
		Amount: func(atk *info.AttackEvent, t info.Target) ([]float64, bool) {
			if atk.Info.AttackTag != attacks.AttackTagElementalArt {
				return nil, false
			}
			// Can't be triggered by itself when refreshing
			if atk.Info.Abil == skillAbilInitial {
				return nil, false
			}
			if e, ok := t.(*enemy.Enemy); !(ok && e.HP()/e.MaxHP() < .5) {
				return nil, false
			}
			return m, true
		},
	})

	if !c.IsHexerei {
		return
	}

	if c.Core.Player.GetHexereiCount() < 2 {
		return
	}

	c.Core.Events.Subscribe(event.OnEnemyHit, func(args ...any) bool {
		atk := args[1].(*info.AttackEvent)
		if atk.Info.ActorIndex != c.Index() {
			return false
		}

		if atk.Info.AttackTag != attacks.AttackTagElementalArt {
			return false
		}

		if atk.Info.Abil == skillAbilInitial {
			return false
		}

		if c.getAureliths() < 1 {
			return false
		}
		atk.Info.FlatDmg += 2.4 * c.TotalDef(false)

		return false
	}, "albedo-a1-hook")
}

// Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by 125 for 10s.
func (c *char) a4() {
	if c.Base.Ascension < 4 {
		return
	}
	m := make([]float64, attributes.EndStatType)
	m[attributes.EM] = 125
	for _, char := range c.Core.Player.Chars() {
		char.AddStatMod(character.StatMod{
			Base:         modifier.NewBaseWithHitlag("albedo-a4", 600),
			AffectedStat: attributes.EM,
			Amount: func() ([]float64, bool) {
				return m, true
			},
		})
	}
}

func (c *char) getAureliths() int {
	count := 0
	for _, exp := range c.aureliths {
		if exp >= c.Core.F {
			count += 1
		}
	}
	return count
}

func (c *char) createAurelith() {
	if c.getAureliths() >= 2 {
		return
	}
	if c.Core.Flags.LogDebug {
		c.Core.Log.NewEventBuildMsg(glog.LogCharacterEvent, c.Index(), "Creating aurelith").Write("expires", c.Core.F+10*60)
	}

	c.aureliths[c.oldestAurelith] = c.Core.F + 10*60
	c.oldestAurelith = (c.oldestAurelith + 1) % 2
	c.hexereiOnAurelith()
}

func (c *char) hexereiInit() {
	if !c.IsHexerei {
		return
	}

	if c.Core.Player.GetHexereiCount() < 2 {
		return
	}

	c.hexereiBuff = make([]float64, attributes.EndStatType)

	c.Core.Events.Subscribe(event.OnEnemyDamage, func(args ...any) bool {
		atk := args[1].(*info.AttackEvent)
		if atk.Info.ActorIndex != c.Index() {
			return false
		}

		if atk.Info.AttackTag != attacks.AttackTagElementalArt {
			return false
		}

		if !c.StatusIsActive(hexereiSkillKey) {
			return false
		}

		c.createAurelith()
		return false
	}, "albedo-hexerei-aurelith")
}

func (c *char) hexereiOnSkill() {
	if !c.IsHexerei {
		return
	}

	if c.Core.Player.GetHexereiCount() < 2 {
		return
	}
	c.AddStatus(hexereiSkillKey, 20*60, true)
}

func (c *char) hexereiOnIsotoma() {
	if !c.IsHexerei {
		return
	}

	if c.Core.Player.GetHexereiCount() < 2 {
		return
	}

	for _, char := range c.Core.Player.Chars() {
		char.AddAttackMod(character.AttackMod{
			Base: modifier.NewBase(hexereiIsotomaKey, 20*60),
			Amount: func(atk *info.AttackEvent, t info.Target) ([]float64, bool) {
				switch atk.Info.AttackTag {
				case attacks.AttackTagNormal,
					attacks.AttackTagExtra,
					attacks.AttackTagPlunge,
					attacks.AttackTagElementalArt,
					attacks.AttackTagElementalArtHold,
					attacks.AttackTagElementalBurst:
				default:
					return nil, false
				}
				c.hexereiBuff[attributes.DmgP] = min(c.TotalDef(true)/1000*0.04, 0.12)
				return c.hexereiBuff, true
			},
		})
	}
}

func (c *char) hexereiOnAurelith() {
	for _, char := range c.Core.Player.Chars() {
		char.AddAttackMod(character.AttackMod{
			Base: modifier.NewBase(hexereiAurelithKey, 20*60),
			Amount: func(atk *info.AttackEvent, t info.Target) ([]float64, bool) {
				if !c.Core.Player.ByIndex(atk.Info.ActorIndex).IsHexerei {
					return nil, false
				}

				switch atk.Info.AttackTag {
				case attacks.AttackTagNormal,
					attacks.AttackTagExtra,
					attacks.AttackTagPlunge,
					attacks.AttackTagElementalArt,
					attacks.AttackTagElementalArtHold,
					attacks.AttackTagElementalBurst:
				default:
					return nil, false
				}
				c.hexereiBuff[attributes.DmgP] = min(c.TotalDef(true)/1000*0.1, 0.30)
				return c.hexereiBuff, true
			},
		})
	}
}
