package_name: aino
genshin_id: 10000121
key: aino
icd_groups:
  - group_name: ICDGroupAinoBurstEnhanced
    reset_timer: 108
    ele_app_sequence:
      [1, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
    attack: # Bish-Bash-Bosh Repair
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}×2
            - 2 # 3-Hit DMG|{param2:F1P}×2
    skill: # Musecatcher
        skill_1:
            - 0 # Stage 1 DMG|{param0:F1P}
        skill_2:
            - 1 # Stage 2 DMG|{param1:F1P}
    burst: # Precision Hydronic Cooler
        burst:
            - 0 # Water Ball DMG|{param0:F1P}
