// Code generated by "pipeline"; DO NOT EDIT.
package vodyanitsa

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"travel"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Vodyanitsa, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
		attack_4,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
        0.4338,
        0.4664,
        0.4989,
        0.5423,
        0.5748,
        0.6074,
        0.6508,
        0.6942,
        0.7375,
        0.7809,
        0.8243,
        0.8677,
        0.9219,
        0.9762,
        1.0304,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
        0.4023,
        0.4325,
        0.4627,
        0.5029,
        0.5331,
        0.5632,
        0.6035,
        0.6437,
        0.6839,
        0.7242,
        0.7644,
        0.8046,
        0.8549,
        0.9052,
        0.9555,
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
        0.493,
        0.53,
        0.567,
        0.6163,
        0.6532,
        0.6902,
        0.7395,
        0.7888,
        0.8381,
        0.8874,
        0.9367,
        0.986,
        1.0477,
        1.1093,
        1.1709,
	}
	// attack: attack_4 = [3]
	attack_4 = []float64{
        0.6556,
        0.7048,
        0.754,
        0.8195,
        0.8687,
        0.9179,
        0.9834,
        1.049,
        1.1146,
        1.1801,
        1.2457,
        1.3113,
        1.3932,
        1.4752,
        1.5571,
	}
	// attack: charge = [3 4]
	charge = []float64{
        1.2376,
        1.3304,
        1.4232,
        1.547,
        1.6398,
        1.7326,
        1.8564,
        1.9802,
        2.1039,
        2.2277,
        2.3514,
        2.4752,
        2.6299,
        2.7846,
        2.9393,
	}
	// skill: skill = [0]
	skill = []float64{
        0.0327,
        0.0352,
        0.0376,
        0.0409,
        0.0434,
        0.0458,
        0.0491,
        0.0524,
        0.0556,
        0.0589,
        0.0622,
        0.0654,
        0.0695,
        0.0736,
        0.0777,
	}
	skillHealFlat = []float64{
        270.0,
        297.0,
        326.0,
        357.0,
        391.0,
        427.0,
        465.0,
        506.0,
        548.0,
        593.0,
        640.0,
        690.0,
        742.0,
        795.0,
        852.0,
	}
	skillHealRatio = []float64{
 		0.028,
        0.0301,
        0.0322,
        0.035,
        0.0371,
        0.0392,
        0.042,
        0.0448,
        0.0476,
        0.0504,
        0.0532,
        0.056,
        0.0595,
        0.063,
        0.0665,
	}
	skillShred = []float64{
		0.143,
        0.156,
        0.169,
        0.182,
        0.195,
        0.208,
        0.221,
        0.234,
        0.247,
        0.26,
        0.2756,
        0.2912,
        0.3068,
        0.3224,
        0.338,
	}
	// burst: burst = [0]
	burst = []float64{
		0.4568,
        0.491,
        0.5253,
        0.571,
        0.6052,
        0.6395,
        0.6852,
        0.7308,
        0.7765,
        0.8222,
        0.8679,
        0.9135,
        0.9706,
        1.0277,
        1.0848,
	}
	// burst: burstBonus = [1]
	burstBonus = []float64{
        0.48,
        0.516,
        0.552,
        0.6,
        0.636,
        0.672,
        0.72,
        0.768,
        0.816,
        0.864,
        0.912,
        0.96,
        1.02,
        1.08,
        1.14,
	}
)
