id: 10000129
key: "lohen"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_MONDSTADT
element: Ice
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Lohen"
stats: {
   base_hp: 1000.986
   base_atk: 26.8128
   base_def: 61.0266
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 858.255
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52.326
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.987871
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1468.0677
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 89.505
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.32136
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2281.1514
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 139.077
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.099342
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2890.964
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 176.256
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.43283
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3500.7769
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 213.435
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.76632
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4110.59
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 250.614
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 110.09981
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 11292
   burst: 11295
   attack: 11291
   burst_energy_cost: 60
}
name_text_hash_map: 2872823194
