// Code generated by "pipeline"; DO NOT EDIT.
package lohen

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"travel"},
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Lohen, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		{attack_2},
		attack_3,
		{attack_4},
		attack_5,
	}
	skillAttack = [][][]float64{
		{skillAttack_1},
		{skillAttack_2},
		skillAttack_3,
		{skillAttack_4},
		skillAttack_5,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
        0.5399,
        0.5839,
        0.6278,
        0.6906,
        0.7345,
        0.7848,
        0.8538,
        0.9229,
        0.9919,
        1.0673,
        1.1426,
        1.2180,
        1.2933,
        1.3686,
        1.4440,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
        0.5644,
        0.6104,
        0.6563,
        0.7219,
        0.7679,
        0.8204,
        0.8926,
        0.9648,
        1.0370,
        1.1157,
        1.1945,
        1.2732,
        1.3520,
        1.4308,
        1.5095,
	}
	// attack: attack_4 = [3 3 3]
	attack_3 = [][]float64{
		{
			0.2542,
			0.2749,
			0.2956,
			0.3251,
			0.3458,
			0.3695,
			0.4020,
			0.4345,
			0.4670,
			0.5025,
			0.5380,
			0.5734,
			0.6089,
			0.6444,
			0.6798,
		},
		{
			0.2542,
			0.2749,
			0.2956,
			0.3251,
			0.3458,
			0.3695,
			0.4020,
			0.4345,
			0.4670,
			0.5025,
			0.5380,
			0.5734,
			0.6089,
			0.6444,
			0.6798,
		},
		{
			0.2542,
			0.2749,
			0.2956,
			0.3251,
			0.3458,
			0.3695,
			0.4020,
			0.4345,
			0.4670,
			0.5025,
			0.5380,
			0.5734,
			0.6089,
			0.6444,
			0.6798,
		},
	}

	// attack: attack_5 = [4]
	attack_4 = []float64{
        0.2542,
        0.2749,
        0.2956,
        0.3251,
        0.3458,
        0.3695,
        0.4020,
        0.4345,
        0.4670,
        0.5025,
        0.5380,
        0.5734,
        0.6089,
        0.6444,
        0.6798,
	}
		// attack: attack_3 = [2 2]
	attack_5 = [][]float64{
		{
			0.3686,
			0.3986,
			0.4286,
			0.4714,
			0.5014,
			0.5357,
			0.5829,
			0.6300,
			0.6772,
			0.7286,
			0.7800,
			0.8314,
			0.8829,
			0.9343,
			0.9857,
		},
		{
			0.5529,
			0.5979,
			0.6429,
			0.7072,
			0.7522,
			0.8036,
			0.8743,
			0.9450,
			1.0157,
			1.0929,
			1.1700,
			1.2472,
			1.3243,
			1.4015,
			1.4786,
		},
	}
	// attack: charge = [4]
	charge = []float64{
        0.6588,
        0.7124,
        0.7660,
        0.8426,
        0.8962,
        0.9575,
        1.0418,
        1.1260,
        1.2103,
        1.3022,
        1.3941,
        1.4860,
        1.5780,
        1.6699,
        1.7618,
	}
	// attack: attack_1 = [0]
	skillAttack_1 = []float64{
        0.6749,
        0.7298,
        0.7848,
        0.8632,
        0.9182,
        0.9810,
        1.0673,
        1.1536,
        1.2399,
        1.3341,
        1.4283,
        1.5224,
        1.6166,
        1.7108,
        1.8050,
	}
	// attack: attack_2 = [1]
	skillAttack_2 = []float64{
        0.7055,
        0.7630,
        0.8204,
        0.9024,
        0.9599,
        1.0255,
        1.1157,
        1.2060,
        1.2962,
        1.3947,
        1.4931,
        1.5916,
        1.6900,
        1.7884,
        1.8869,
	}
	// attack: attack_4 = [3 3 3]
	skillAttack_3 = [][]float64{
		{
			0.3177,
			0.3436,
			0.3695,
			0.4064,
			0.4323,
			0.4618,
			0.5025,
			0.5431,
			0.5838,
			0.6281,
			0.6724,
			0.7168,
			0.7611,
			0.8055,
			0.8498,
		},
		{
			0.3177,
			0.3436,
			0.3695,
			0.4064,
			0.4323,
			0.4618,
			0.5025,
			0.5431,
			0.5838,
			0.6281,
			0.6724,
			0.7168,
			0.7611,
			0.8055,
			0.8498,
		},
		{
			0.3177,
			0.3436,
			0.3695,
			0.4064,
			0.4323,
			0.4618,
			0.5025,
			0.5431,
			0.5838,
			0.6281,
			0.6724,
			0.7168,
			0.7611,
			0.8055,
			0.8498,
		},
	}
	skillAttack_4 = []float64{
        0.9403,
        1.0169,
        1.0934,
        1.2027,
        1.2793,
        1.3668,
        1.4870,
        1.6073,
        1.7276,
        1.8588,
        1.9900,
        2.1212,
        2.2524,
        2.3836,
        2.5148,
	}
	skillAttack_5 = [][]float64{
		{
			0.4607,
			0.4982,
			0.5357,
			0.5893,
			0.6268,
			0.6697,
			0.7286,
			0.7875,
			0.8464,
			0.9107,
			0.9750,
			1.0393,
			1.1036,
			1.1679,
			1.2322,
		},
		{
			0.6911,
			0.7473,
			0.8036,
			0.8839,
			0.9402,
			1.0045,
			1.0929,
			1.1813,
			1.2697,
			1.3661,
			1.4625,
			1.5590,
			1.6554,
			1.7518,
			1.8483,
		},
	}
	skillCharge = []float64{
        0.8235,
        0.8905,
        0.9575,
        1.0532,
        1.1203,
        1.1969,
        1.3022,
        1.4075,
        1.5129,
        1.6278,
        1.7427,
        1.8576,
        1.9725,
        2.0873,
        2.2023,
	}
	// skill: skillInital = [0]
	skillPierce = []float64{
        0.5000,
        0.5375,
        0.5750,
        0.6250,
        0.6625,
        0.7000,
        0.7500,
        0.8000,
        0.8500,
        0.9000,
        0.9500,
        1.0000,
        1.0625,
        1.1250,
        1.1875,
	}
	// burst: burst = [0]
	burst = []float64{
        0.9506,
        1.0219,
        1.0932,
        1.1883,
        1.2596,
        1.3309,
        1.4260,
        1.5210,
        1.6161,
        1.7112,
        1.8062,
        1.9013,
        2.0201,
        2.1389,
        2.2578,
	}
)
