id: 10000127
key: "illuga"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_NODKRAI
element: Rock
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Illuga"
stats: {
   base_hp: 1002.9701
   base_atk: 16.0272
   base_def: 68.2122
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 749.27
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 50.958
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 11.97342
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1281.6461
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.165
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.48085
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1991.4808
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 135.441
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 31.82409
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2523.857
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.648
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.33152
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3056.233
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 207.855
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 48.83895
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3588.6091
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 244.062
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.34638
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 11272
   burst: 11275
   attack: 11271
   burst_energy_cost: 60
}
name_text_hash_map: 102656986
