id: 10000126
key: "zibai"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_NODKRAI_ZIBAI
element: Rock
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Zibai"
stats: {
   base_hp: 1005.7526
   base_atk: 17.5028
   base_def: 74.48835
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 862.3419
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 63.8685
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.006
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1475.0585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 109.2488
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.6681
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2292.014
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 169.7558
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.8843
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2904.7307
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 215.136
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.5464
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3517.4473
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 260.5163
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.2086
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4130.164
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 305.8965
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 71.8707
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 11262
   burst: 11265
   attack: 11261
   burst_energy_cost: 60
}
name_text_hash_map: 937532578
