name: deployment build
on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup + test go and yarn
      - uses: actions/checkout@v3
      - name: go-setup-and-test
        uses: ./.github/actions/go-setup-and-test

      # binaries
      - name: Build Binary
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/scripts/build.sh"
          # run the script
          "${GITHUB_WORKSPACE}/scripts/build.sh"
        env:
          GCSIM_SHARE_KEY: ${{ secrets.AES_KEY }}

      # move binaries we care about to 1 folder
      - name: consolidate binariesi
        run: mkdir artifacts

      - name: move binaries
        run: |
          mv gcsim_windows_amd64.exe ./artifacts/
          mv server_windows_amd64.exe ./artifacts/

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: nightly
          path: artifacts
